name: Verify
on:
    push:    
        branches:
            - main
            - develop
        paths:
            - 'src/**'
            - 'structures/**'
            - 'main.go'
            - 'go.*'

permissions:
    contents: read
    packages: read
    statuses: write
    pull-requests: write

jobs:
    golangci:
      name: Lint Backend
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v4
          with:
            go-version: '1.21'
            cache: false

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54
            working-directory: ./
            args: --timeout=30m --config=./.golangci.yml --issues-exit-code=1 --color=always
            only-new-issues: true
            skip-cache: true
            skip-pkg-cache: true
            skip-build-cache: true